---

version: "2"

checks:
  file-lines:
    config:
      threshold: 370

  method-complexity:
    config:
      threshold: 13

  method-count:
    config:
      threshold: 25

  return-statements:
    config:
      threshold: 5

  similar-code:
    enabled: false

exclude_patterns:
  - .bundle/
  - coverage/
  - doc/
  - tmp/
